# Generated by Django 4.2.20 on 2025-06-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplistpage', '0003_property_user'),
        ('userAccount', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='proplistpage.property'),
        ),
    ]
