# Generated by Django 4.2.20 on 2025-06-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_userprofile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
