# Generated by Django 4.2.20 on 2025-06-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
