# Generated by Django 4.2.20 on 2025-06-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proplistpage', '0002_property_is_booked_property_type'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proplistpage.property'),
        ),
    ]
