# Generated by Django 5.2.1 on 2025-06-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_calculator', '0002_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
