# Generated by Django 4.2.20 on 2025-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proplistpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
    ]
