# Generated by Django 4.2.20 on 2025-06-20 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_attachments/'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('HVAC', 'HVAC'), ('General Maintenance', 'General Maintenance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
